# Generated by Django 2.1.2 on 2018-10-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrados',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
